/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Backgrounds */
        'background':   'var(--background)',
        'bg-hero':      'var(--bg-hero)',
        'bg-section':   'var(--bg-section)',
        'bg-deep':      'var(--bg-deep)',
        'surface':      'var(--surface)',
        /* Blue spectrum & Brand */
        'navy':         'var(--navy)',
        'sapphire':     'var(--sapphire)',
        'primary':      'var(--primary)',
        'royal':        'var(--royal)',
        'electric':     'var(--electric)',
        'sky-blue':     'var(--sky)',
        'cornflower':   'var(--cornflower)',
        'powder':       'var(--powder)',
        'ice':          'var(--ice)',
        'frost':        'var(--frost)',
        'mist':         'var(--mist)',
        /* Text */
        'text':         'var(--text)',
        'text-dim':     'var(--text-dim)',
        'text-subtle':  'var(--text-subtle)',
        'text-on-dark': 'var(--text-on-dark)',
        /* Borders */
        'border-color': 'var(--border)',
        'border-light': 'var(--border-light)',

        /* Stitch Specific Design Tokens */
        'inverse-primary': '#005ac2',
        'primary-fixed-dim': '#adc6ff',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#00285d',
        'on-background': '#dae3f6',
        'outline': '#8c909f',
        'error-container': '#93000a',
        'surface-container-low': '#070707',
        'on-primary-fixed-variant': '#004395',
        'surface-variant': '#2d3544',
        'tertiary': '#c0c1ff',
        'on-secondary-container': '#00374d',
        'secondary-container': '#00a6e0',
        'on-secondary-fixed-variant': '#004c69',
        'on-error': '#690005',
        'inverse-surface': '#dae3f6',
        'surface-container-high': '#0f0f0f',
        'secondary': '#7bd0ff',
        'surface-bright': '#313948',
        'on-secondary-fixed': '#001e2c',
        'on-surface': '#dae3f6',
        'tertiary-fixed-dim': '#c0c1ff',
        'surface-container': '#0a0a0a',
        'inverse-on-surface': '#28313f',
        'glass-bg': 'rgba(0, 0, 0, 0.6)',
        'on-primary': '#002e6a',
        'surface-dim': '#000000',
        'outline-variant': '#424754',
        'secondary-fixed-dim': '#7bd0ff',
        'surface-container-highest': '#2d3544',
        'glass-stroke': 'rgba(255, 255, 255, 0.1)',
        'cyan-glow': '#22D3EE',
        'tertiary-container': '#8083ff',
        'on-surface-variant': '#c2c6d6',
        'primary-fixed': '#d8e2ff',
        'primary-container': '#4d8eff',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'on-tertiary': '#1000a9',
        'surface-tint': '#adc6ff',
        'secondary-fixed': '#c4e7ff',
        'surface-container-lowest': '#000000',
        'on-secondary': '#00354a',
        'on-tertiary-container': '#0d0096',
        'tertiary-fixed': '#e1e0ff',
        'error': '#ffb4ab',
        'on-tertiary-fixed': '#07006c',
        'on-primary-fixed': '#001a42'
      },
      fontFamily: {
        sans:    ['Inter', 'sans-serif'],
        heading: ['Hanken Grotesk', 'sans-serif'],
        display: ['Hanken Grotesk', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'label-code': ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'fade-up':    'fadeUp 0.7s ease-out forwards',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'blink':      'blink 1s infinite',
      },
      keyframes: {
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        blink: {
          '0%,100%': { opacity: '1' },
          '50%':     { opacity: '0' },
        },
      },
      boxShadow: {
        'blue-sm':  '0 2px 8px rgba(37,99,235,0.08)',
        'blue-md':  '0 4px 24px rgba(37,99,235,0.12)',
        'blue-lg':  '0 8px 40px rgba(37,99,235,0.18)',
        'sky-md':   '0 4px 24px rgba(14,165,233,0.15)',
        'navy-md':  '0 4px 24px rgba(30,58,138,0.15)',
      },
    },
  },
  plugins: [],
}
